build: fix running vue frontend in development
Running "Launch Vue Frontend build watcher" command was giving this error:

"""
ERROR in /workspace/frontend/AdbNav.vue.ts(67,27)
      TS2591: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i @types/node` and then add `node` to the types field in your tsconfig.
"""

Running "npm i @types/node" with legacy-peer-deps fixed it.